spring:
    application:
      name: LibraryApi
      datasource:
        url: jdbc:postgres://localhost:5432:library
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
      Jpa:
        hibernate:
          ddl-auto: update
